config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: "registrations" }

  root to: 'pages#home'
  get '/wikihow', to: 'pages#wikihow'
  get '/my_final_tracks', to: 'users#my_final_tracks'


resources :channels, only: [ :show ]
get "channel/show", to: 'channels#show'

  resources :users, only: [:edit, :update, :show, :index]

  resources :tracks, only: [:new, :create] do
    resources :requests, only: [:new, :create]
  end
  get :my_requests, to: "requests#my_requests"
  get :my_submissions, to: "submissions#my_submissions"
  resources :requests, only: [:show, :index, :edit, :update, :destroy] do
    resources :submissions, only: [:new, :create, :update]
  end
  resources :submissions, only: [:show, :index, :edit, :update, :destroy]
  resources :request_timecodes, only: [ :update ]
  patch '/submissions/:id/accept', to: "submissions#accept", as: :accept_submission

  mount ActionCable.server => '/cable'
  
  # Health check endpoint for Render deployment
  get '/health', to: proc { [200, {}, ['OK']] }
  
  # API routes
  namespace :api do
    namespace :v1 do
      resources :requests, only: [:index, :show] do
        member do
          get :submissions
        end
      end
    end
  end
end

app/models/request.rb
class Request < ApplicationRecord
  include PgSearch::Model

  belongs_to :instrument
  belongs_to :track
  has_one :user, through: :track
  has_one :genre, through: :track
  has_many :submissions, dependent: :destroy
  validates :description, presence: true

  # Standard ordering - most recent first

  pg_search_scope :search_by_instrument_and_genre,
                  associated_against: {
                    instrument: [:name],
                    genre: :name
                  },
                  using: {
                    tsearch: { prefix: true }
                  }
end

app/controllers/api/v1/requests_controller.rb
class Api::V1::RequestsController < Api::V1::BaseController
  before_action :set_request, only: [:show]
  
  # GET /api/v1/requests
  def index
    @requests = Request.includes(:instrument, :track => [:user, :genre])
    
    if params[:query].present?
      @requests = @requests.search_by_instrument_and_genre(params[:query])
    end
    
    render_success({
      requests: @requests.map { |request| format_request(request) }
    })
  end

  # GET /api/v1/requests/1
  def show
    render_success({
      request: format_request(@request)
    })
  end

  # DELETE endpoint removed - no deletion functionality needed currently

  private

  def set_request
    @request = Request.find(params[:id])
  rescue ActiveRecord::RecordNotFound
    render_error('Request not found', :not_found)
  end
  
  def format_request(request)
    {
      id: request.id,
      description: request.description,
      created_at: request.created_at,
      updated_at: request.updated_at,
      instrument: {
        id: request.instrument.id,
        name: request.instrument.name
      },
      track: {
        id: request.track.id,
        name: request.track.name,
        bpm: request.track.bpm,
        time_signature: request.track.time_signature,
        key: request.track.key,
        file_url: request.track.file&.url,
        user: {
          id: request.track.user.id,
          first_name: request.track.user.first_name,
          last_name: request.track.user.last_name
        },
        genre: request.track.genre ? {
          id: request.track.genre.id,
          name: request.track.genre.name
        } : nil
      },
      submissions_count: request.submissions.count
    }
  end
end

app/controllers/requests_controller.rb
class RequestsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index]

  def index
    @requests = Request.all
    if params[:query].present?
      @requests = Request.search_by_instrument_and_genre(params[:query])
    else
      @requests = Request.all
    end
  end

  def show
    @request = Request.find(params[:id])
  end

  def my_requests
    @requests = current_user.requests
  end

  def new
    @track = Track.find(params[:track_id])
    @request = Request.new
  end

  def create
    @request = Request.new(request_params)
    @track = Track.find(params[:track_id])
    @request.track = Track.find(params[:track_id])
    @request.instrument = Instrument.find(params[:request][:instrument_id])
    if @request.save
      redirect_to request_path(@request)
    else
      render :new
    end
  end

  def update
    @request = Request.find(params[:id])
    if @request.update(request_params)
      redirect_to request_path(@request)
    else
      render :show
    end
  end

  def destroy
    @request = Request.find(params[:id])
    @request.destroy
    redirect_to my_requests_path
  end

  private

  def request_params
    params.require(:request).permit(:description, :instrument_id, :final_track)
  end

  def submission_params
    params.require(:submission).permit(:description, :name, :selected, :bpm, :time_signature, :key, :file)
  end
end

app/views/requests/index.html.erb
<div class="container">
  <div class="lockup-title d-flex justify-content-between">
    <div class="index-title">
      <h1><b class="number-high"><%= @requests.count %></b> tracks you can collaborate on.</h1>
      <br>
      <p class="text-title-index">Click on a track to begin a collaboration request with other artists on our platform</p>
    </div>

    <div class="row justify-content-center">
      <div class="index-call-to-action">
        <%#= link_to "+ Add a new request", new_track_path, class: "btn btn-soft" %>
      </div>
    </div>
  </div>
  <div class="index-cards">
    <% @requests.each do |request| %>
      <%= link_to request_path(request) do %>
        <%= render 'shared/track', track: request.track %>
      <% end %>
    <% end %>
  </div>
</div>

app/views/requests/my_requests.html.erb
<div class="container">
  <div class="title-container">
    <h1>My Collaboration Track Requests: </h1>
  </div>
  <% @requests.each do |request| %>
    <p class="description">Description: <%= request.description %></p>
  <%= link_to request_path(request) do %>
    <%= render 'shared/track', track: request.track %>
    <% end %>
    <%= link_to 'Delete request', request_path(request), method: :delete, data: { confirm: "Are you sure you want to Delete your request?" }, class: "btn btn-delete" %>
  <% end %>
</div>

app/views/requests/new.html.erb
<div class="container">
  <div class="request-new-title text-center">
    <h1>Congratulations you've added a track!</h1>
    <h2>Now create a request!</h2>
  </div>

  <div class="tracks-form">
    <%= simple_form_for ([@track, @request]) do |r| %>
      <%= r.input :description %>
      <%= r.association :instrument,
                        label: "Which instrument do you need?",
                        required: false,
                        selected: Instrument.first %>
      <%= r.submit "Submit your request",
                   class: "btn btn-primary my-4" %>
    <% end %>
  </div>
</div>

app/views/requests/show.html.erb
<div class="container" id="request-show-container">
    <div class="request-show-back">
    <%= link_to "Back", requests_path, class: "btn btn-back" %>
  </div>
  <div class="index-cards">
  <%= render 'shared/track', track: @request.track %>
  </div>

  <div class="request-show-header d-flex justify-content-between">
    <div>
      <h1>Collaborate with <%= @request.track.user.username %></h1>
      <h4><%= @request.description %></h4>
    </div>

    <div>
      <% if current_user != @request.track.user %>
          <%= link_to "UPLOAD", new_request_submission_path(@request), class: "btn btn-light btn-light-2" %>
        <% else %>
          <% unless @request.submissions.where(selected: true).empty? %>
            <%= simple_form_for(@request) do |f| %>
            <%= f.input :final_track, label: "Paste your final track URL" %>
            <%= f.submit "Submit Final Track", class: "btn btn-light" %>
          <% end %>
        <% end %>
      <% end %>
    </div>

    <% if @request.final_track %>
      <div class="final_track">
          <iframe width="100%" height="300" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=<%= @request.final_track %>&color=%23ff5500&auto_play=false&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true&visual=true"></iframe>
      </div>
      <% end %>
  </div>

  <div class="request-show-submissions">
    <div class="request-show-submissions-header">
      <h2>Submissions</h2>
      <br>
      <% if current_user != @request.track.user %>
      <h4>If you would like to submit a collaboration request remember to follow these steps:</h4>
        <br>
        <ul>
          <li><h4>Listen to the track</h4></li>
          <li><h4>Read the description</h4></li>
          <li><h4>Use the correct insrument</h4></li>
          <li><h4>Record at the same bpm, key and time signature</h4></li>
          <li><h4>Remember to always start recording from 0! </h4></li>
        </ul>
      <br>
      <br>
      <% end %>
    </div>
    <% @request.submissions.each do |submission|  %>
      <%= render 'shared/submission_card', submission: submission %>
    <% end %>
  </div>
</div>