config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: "registrations" }

  root to: 'pages#home'
  get '/wikihow', to: 'pages#wikihow'
  get '/my_final_tracks', to: 'users#my_final_tracks'


resources :channels, only: [ :show ]
get "channel/show", to: 'channels#show'

  resources :users, only: [:edit, :update, :show, :index]

  resources :tracks, only: [:new, :create] do
    resources :requests, only: [:new, :create]
  end
  get :my_requests, to: "requests#my_requests"
  get :my_submissions, to: "submissions#my_submissions"
  resources :requests, only: [:show, :index, :edit, :update, :destroy] do
    resources :submissions, only: [:new, :create, :update]
  end
  resources :submissions, only: [:show, :index, :edit, :update, :destroy]
  resources :request_timecodes, only: [ :update ]
  patch '/submissions/:id/accept', to: "submissions#accept", as: :accept_submission

  mount ActionCable.server => '/cable'
  
  # Health check endpoint for Render deployment
  get '/health', to: proc { [200, {}, ['OK']] }
  
  # API routes
  namespace :api do
    namespace :v1 do
      resources :requests, only: [:index, :show] do
        member do
          get :submissions
        end
      end
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/channel.rb
class Channel < ApplicationRecord
  has_many :messages
end

app/models/final_track.rb
class FinalTrack < ApplicationRecord
  belongs_to :user
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :user_genres
end

app/models/instrument.rb
class Instrument < ApplicationRecord
  has_many :requests
  has_many :submissions
  has_many :user_instruments
  has_many :users, through: :user_instruments
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :channel

  validates :content, presence: true

  after_create :broadcast_message

  def as_json(_options = {})
    nickname = user.nickname.nil? ? user.email.match(/[^@]+/)[0] : user.nickname

    {
      id: id,
      author: nickname,
      content: content,
      created_at: created_at,
      channel: channel.name
    }
  end

  private

  def broadcast_message
    ActionCable.server.broadcast("channel_#{channel.name}", self)
  end
end

app/models/request.rb
class Request < ApplicationRecord
  include PgSearch::Model

  belongs_to :instrument
  belongs_to :track
  has_one :user, through: :track
  has_one :genre, through: :track
  has_many :submissions, dependent: :destroy
  validates :description, presence: true

  # Standard ordering - most recent first

  pg_search_scope :search_by_instrument_and_genre,
                  associated_against: {
                    instrument: [:name],
                    genre: :name
                  },
                  using: {
                    tsearch: { prefix: true }
                  }
end

app/models/submission.rb
class Submission < ApplicationRecord
  mount_uploader :file, FileUploader
  belongs_to :user
  belongs_to :request

  default_scope { order(created_at: :desc) }

  validates :description, presence: true, length: { in: 10..200,
                                                    message: " must be between 10 - 200 characters." }
  validates :file, presence: true
end

app/models/track.rb
class Track < ApplicationRecord
  mount_uploader :file, FileUploader
  belongs_to :user
  has_many :requests
  has_many :submissions
  belongs_to :genre, optional: true

  validates :name, presence: true
  validates :bpm, presence: true
  validates :time_signature, presence: true
  validates :key, presence: true
  # validates :duration, presence: true
  validates :file, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  mount_uploader :photo, PhotoUploader
  has_many :tracks
  has_many :user_instruments
  has_many :instruments, through: :user_instruments
  has_many :requests, through: :tracks
  has_many :submissions
  has_many :user_genres
  has_many :genres, through: :user_genres
  has_many :final_tracks
  has_many :messages
end

app/models/user_genre.rb
class UserGenre < ApplicationRecord
  belongs_to :genre
  belongs_to :user
end

app/models/user_instrument.rb
class UserInstrument < ApplicationRecord
  belongs_to :user
  belongs_to :instrument
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!

  def default_url_options
    { host: ENV["DOMAIN"] || "localhost:3000" }
  end
end

app/controllers/channels_controller.rb
class ChannelsController < ApplicationController
  def show
    if params[:id].blank?
      redirect_to channel_path(Channel.first.name)
    else
      @channel = Channel.find_by(name: params[:id])
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home]

  def home
  end
end

app/controllers/requests_controller.rb
class RequestsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index]

  def index
    @requests = Request.all
    if params[:query].present?
      @requests = Request.search_by_instrument_and_genre(params[:query])
    else
      @requests = Request.all
    end
  end

  def show
    @request = Request.find(params[:id])
  end

  def my_requests
    @requests = current_user.requests
  end

  def new
    @track = Track.find(params[:track_id])
    @request = Request.new
  end

  def create
    @request = Request.new(request_params)
    @track = Track.find(params[:track_id])
    @request.track = Track.find(params[:track_id])
    @request.instrument = Instrument.find(params[:request][:instrument_id])
    if @request.save
      redirect_to request_path(@request)
    else
      render :new
    end
  end

  def update
    @request = Request.find(params[:id])
    if @request.update(request_params)
      redirect_to request_path(@request)
    else
      render :show
    end
  end

  def destroy
    @request = Request.find(params[:id])
    @request.destroy
    redirect_to my_requests_path
  end

  private

  def request_params
    params.require(:request).permit(:description, :instrument_id, :final_track)
  end

  def submission_params
    params.require(:submission).permit(:description, :name, :selected, :bpm, :time_signature, :key, :file)
  end
end

app/controllers/tracks_controller.rb
class TracksController < ApplicationController
  def new
    @track = Track.new
  end

  def create
    @track = Track.new(track_params)
    @track.user = current_user
    if @track.save
      redirect_to new_track_request_path(@track)
    else
      render :new
    end
  end

  def destroy
    @track = Track.find(params[:id])
    @track.desroy
  end

  private

  def track_params
    params.require(:track).permit(:name, :bpm, :time_signature, :key, :duration, :file, :genre_id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def my_final_tracks
    @requests = current_user.requests
  end

  def update
    @user = User.find(params[:id])
    instruments = Instrument.where(id: params[:user][:instruments])
    @user.instruments = instruments
    genres = Genre.where(id: params[:user][:genres])
    @user.genres = genres

    if @user.update(user_params)
      redirect_to user_path
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:username, :first_name, :last_name, :biography, :instruments, :genres, :photo)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/meta_tags_helper.rb
# app/helpers/meta_tags_helper.rb

module MetaTagsHelper
  def meta_title
    content_for?(:meta_title) ? content_for(:meta_title) : DEFAULT_META["meta_title"]
  end

  def meta_description
    content_for?(:meta_description) ? content_for(:meta_description) : DEFAULT_META["meta_description"]
  end

  def meta_image
    meta_image = (content_for?(:meta_image) ? content_for(:meta_image) : DEFAULT_META["meta_image"])
    # little twist to make it work equally with an asset or a url
    meta_image.starts_with?("http") ? meta_image : image_url(meta_image)
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= render 'application/favicon' %>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css" integrity="sha384-oS3vJWv+0UjzBfQzYUhtDYW+Pj2yciDJxpsK1OYPAYjqT085Qq/1cq5FLXAZQ7Ay" crossorigin="anonymous">
    <title>Collaborate | connects you to artists globally with the talent you need to realise your ideal sound.</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%# <%= stylesheet_link_tag 'application', media: 'all' %> 
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload", media: "all" %>
    <%#= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
        <title><%= meta_title %></title>
    <meta name="description" content="<%= meta_description %>">

    <!-- Facebook Open Graph data -->
    <meta property="og:title" content="<%= meta_title %>" />
    <meta property="og:type" content="website" />
    <meta property="og:url" content="<%= request.original_url %>" />
    <meta property="og:image" content="<%= meta_image %>" />
    <meta property="og:description" content="<%= meta_description %>" />
    <meta property="og:site_name" content="<%= meta_title %>" />

    <!-- Twitter Card data -->
    <meta name="twitter:card" content="summary_large_image">
    <meta name="twitter:site" content="<%= DEFAULT_META["twitter_account"] %>">
    <meta name="twitter:title" content="<%= meta_title %>">
    <meta name="twitter:description" content="<%= meta_description %>">
    <meta name="twitter:creator" content="<%= DEFAULT_META["twitter_account"] %>">
    <meta name="twitter:image:src" content="<%= meta_image %>">
  <!-- This is the new webpacker for rails 7 => jsbundling-rails -->
    <%#= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
    <%= javascript_importmap_tags %> 
  </head>
  <body>
    <% unless action_name == "home" %>
    <%= render 'shared/navbar' %>
    <% end %>
    <%= render 'shared/flashes' %>
    <div class="min-height">
      <%= yield %>
    </div>
    <%#= javascript_include_tag 'application' %>
    <%#= javascript_pack_tag 'application' %> <!-- This is the old webpacker way now using jsbundling-rails -->
    <%= yield :after_js %>
    <%= render 'shared/footer' %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://images.unsplash.com/photo-1470225620780-dba8ba36b745?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1350&q=80);">
  <div class="home-banner-container">
    <h1>Want to finish that track today?</h1>
    <p>Collaborate connects you to artists globally with the talent you need to finish your track and realise your ideal sound.</p>
    <div class="home-btn-container">
    <% if !user_signed_in? %>
      <%= link_to "Start Collaborating", new_user_registration_path, class: "btn btn-light" %>
      <% else %>
      <%= link_to "Continue Collaborating", requests_path, class: "btn btn-light" %>
    <% end %>
    <%= link_to "Check Out Collaborations", requests_path, class: "btn btn-secondary" %>
  </div>
  </div>
</div>

<div class="container">
    <div class="wiki-how-title">
      <h1 class="howto">How to use Collaborate</h1>
      <i class="fas fa-angle-down arrow-down"></i>
    </div>
      <div class="circle-cards">
        <div class="circle-card">
          <img src="https://res.cloudinary.com/beartechnologies/image/upload/v1559635437/collaborate/img_c_zyepu5.jpg">
          <h3 class="info-card-title">Missing a Sound?</h3>
          <p class="paragraph"> Upload your track that has a missing element, describe exactly what you need and collaborate will connect you to musicians with the right skills that can help you. </p>
        </div>
        <div class="circle-card">
          <img src="https://res.cloudinary.com/beartechnologies/image/upload/v1559635437/collaborate/img_b_sr5fqf.jpg" alt="Bass">
          <h3 class="info-card-title">Let The Sound Find You!</h3>
          <p class="paragraph"> Wait for collaborators to post submissions on your track, accept your favorite and then download it. </p>
        </div>

        <div class="circle-card">
          <img src="https://res.cloudinary.com/beartechnologies/image/upload/v1559635437/collaborate/img_a_dj6azx.jpg">
          <h3 class="info-card-title">Mix and Master</h3>
          <p class="paragraph">Drop the submission into your mix, master it and then show the world your new track!</p>
        </div>
      </div>
  </div>

app/views/pages/wikihow.html.erb
<!-- <div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://res.cloudinary.com/beartechnologies/image/upload/v1559680052/Screenshot_2019-06-04_at_22.26.31_xahhfw.png);">
  <div class="container">
    <div class="container">
      <div class="circle-cards">

      </div>
      <%= link_to "Finish your track now!", requests_path, class: "btn btn-light" %>
  </div>
  </div>
</div>



 -->

app/views/shared/_flashes.html.erb
<div class="container">
  <% if notice %>
    <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
      <%= notice %>
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
  <% end %>
  <% if alert %>
    <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
      <%= alert %>
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
  <% end %>
</div>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="https://www.instagram.com/collaborate.today/"><i class="fab fa-instagram"></i></a>
    <a href="https://www.facebook.com/collaborate.today/"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
  </div>
  <div class="footer-copyright">
    <p>Helping Musicians Help Themselves</p> <i class="fas fa-heart"></i>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="right-side-lockup">
      <%= link_to root_path, class: "navbar-brand" do %>
          <%= image_tag "https://res.cloudinary.com/beartechnologies/image/upload/v1559209651/collaborate/c_symbol2_zxudvw.jpg" %>
        <% end %>
    <div class="searchbar">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
        </button>
        <div>
        <form action="/requests" accept-charset="UTF-8" method="get" style="position: relative;" class="form-search">
        <input name="utf8" type="hidden" value="✓">


        <input type="text" name="query" id="query" class="form-control" label="false" placeholder="Search requests" wrapper_html="{:class=>&quot;fas fa-search&quot;}">
         <button type="submit" class="btn btn-link" id="search-btn"><i class="fas fa-search"></i></button>
        </form>
      </div>
    </div>
</div>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to "See all Tracks", requests_path, class: "navbar-actions" %>
        </li>
        <li>
          <%= link_to "Request Collaboration", new_track_path(@track_id), class: "btn btn-light" %>
        </li>


        <li class="nav-item dropdown">
          <button class="btn btn-link" id="navbarDropdown" data-toggle="dropdown" aria-haspopup='true', aria-expanded='false'>
            <i class="fas fa-bars"></i>
          </button>
          <%#= image_tag "https://res.cloudinary.com/beartechnologies/image/upload/v1559291556/collaborate/46262498_ddv3fy.jpg", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Profile", user_path(current_user), class: "dropdown-item" %>
            <%= link_to "My Final Tracks", my_final_tracks_path, class: "dropdown-item" %>
            <%= link_to "My Requests", my_requests_path, class: "dropdown-item" %>
            <%= link_to "My Sumbissions", my_submissions_path, class: "dropdown-item" %>
<!--             <%#= link_to "Chat", channel_show_path, class: "dropdown-item" %>
 -->

            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/shared/_submission_card.html.erb
<div class="submission-card-<%= !submission.nil? && submission.selected ? 'true' : 'false' %>">
    <div class="submission-card-header">
      <div>
        <h4 >Artist:</h4> <h3><%= submission.user.username %></h3>
      </div>
      <div>
        <h4 >Description:</h4> <p><%= submission.description %></p>
      </div>
    </div>

  <div class="submission-card-wav">
    <div id="track_<%= submission.id %>" class="<%= 'waveform-sub' if submission.file %>" data-track-url='<%= submission.file.url(secure: true) %>'></div>
    <div id="wave_timeline_track_<%= submission.id %>"></div>
  </div>

    <% if submission.request.track.user.id == current_user.id && !submission.request.submissions.where(selected: true).any? %>
      <div class="selected-btn">
        <%= link_to 'Accept Collaboration?', accept_submission_path(submission), method: :patch %>
      </div>
    <% elsif submission.request.track.user.id == current_user.id && submission.request.submissions.where(selected: true).any? && submission.selected? %>
      <div class="accepted-text">
        <p>You accepted this submission. Email <%= submission.user.email %> if you want to discuss further.</p>
      </div>
    <% elsif submission.request.track.user.id == current_user.id && submission.request.submissions.where(selected: true).any? && !submission.selected? %>
      <div class="not-accepted-text">
        <p>Not accepted</p>
      </div>
    <% end %>

</div>

app/views/shared/_track.html.erb
 
  <div class="track-card-header">
    <div>
      <h4>Title:</h4> <h3><%= track.name %></h1>
    </div>
    <div>
      <h4>Artist:</h4> <h3><%= track.user.username %></h2>
    </div>
  </div>
<div class="track-card-hull">

  <div class="track-card-wav">
    <div 
    id="track_<%= track.id %>" 
    class="<%= "waveform" if track.file %>" 
    data-track-url='<%= "https://res.cloudinary.com/beartechnologies/#{track['file']} "%>'
    data-request-id='<%= track.requests.first.id %>' 
    data-region-start='<%= track.requests.first&.region_start %>' 
    data-region-end='<%= track.requests.first&.region_end %>'>
    </div>
    <div id="wave_timeline_track_<%= track.id %>"></div>
  </div>

  <div class="track-wav-details">
    <p>bpm: <%= track.bpm %></p>
    <p>Time Signature: <%= track.time_signature %></p>
    <p>Key: <%= track.key %></p>
  </div>
</div>