config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: "registrations" }

  root to: 'pages#home'
  get '/wikihow', to: 'pages#wikihow'
  get '/my_final_tracks', to: 'users#my_final_tracks'


resources :channels, only: [ :show ]
get "channel/show", to: 'channels#show'

  resources :users, only: [:edit, :update, :show, :index]

  resources :tracks, only: [:new, :create] do
    resources :requests, only: [:new, :create]
  end
  get :my_requests, to: "requests#my_requests"
  get :my_submissions, to: "submissions#my_submissions"
  resources :requests, only: [:show, :index, :edit, :update, :destroy] do
    resources :submissions, only: [:new, :create, :update]
  end
  resources :submissions, only: [:show, :index, :edit, :update, :destroy]
  resources :request_timecodes, only: [ :update ]
  patch '/submissions/:id/accept', to: "submissions#accept", as: :accept_submission

  mount ActionCable.server => '/cable'
  
  # Health check endpoint for Render deployment
  get '/health', to: proc { [200, {}, ['OK']] }
  
  # API routes
  namespace :api do
    namespace :v1 do
      resources :requests, only: [:index, :show] do
        member do
          get :submissions
        end
      end
    end
  end
end

app/models/submission.rb
class Submission < ApplicationRecord
  mount_uploader :file, FileUploader
  belongs_to :user
  belongs_to :request

  default_scope { order(created_at: :desc) }

  validates :description, presence: true, length: { in: 10..200,
                                                    message: " must be between 10 - 200 characters." }
  validates :file, presence: true
end

app/controllers/submissions_controller.rb
class SubmissionsController < ApplicationController
  def index
    @submission = Submission.find(params[:user_id]).all
  end

  def new
    @submission = Submission.new
    @request = Request.find(params[:request_id])
  end

  def show
    @submission = Submission.find(params[:id])
  end

  def my_submissions
    @submissions = current_user.submissions
  end

  def create
    @request = Request.find(params[:request_id])
    @submission = Submission.new(submission_params)
    @submission.request = @request
    @submission.user = current_user
    if @submission.save
      redirect_to request_path(@request)
    else
      render :new
    end
  end

  def update
    @submission = Submission.find(params[:id])
    @submission.update(selected: true) if @submission.user != current_user
    redirect_to @submission.request
  end

  def accept
    @submission = Submission.find(params[:id])
    @submission.update(selected: true) if @submission.user != current_user
    redirect_to @submission.request
  end

  def destroy
    @submission = Submission.find(params[:id])
    @submission.destroy
    redirect_to my_submissions_path
  end

  private

  def submission_params
    params.require(:submission).permit(:description, :name, :selected, :bpm, :time_signature, :key, :duration, :file)
  end
end

app/views/submissions/my_submissions.html.erb
<div class="container">
  <h1 class="my-submissions-card-header">My Submissions to Collaboration Requests </h1>
  <div class="card-white-space">
    <% @submissions.each do |submission| %>
      <h2 class="my-submissions-sub-header">Your submission on <%= submission.request.track.user.username %>'s request</h2>
      <p>Description: <%= submission.description %></p>
      <%= link_to request_path(submission.request) do %>
      <%= render 'shared/submission_card', submission: submission %>
      <% end %>
      <%= link_to 'Delete Submission', submission_path(submission), method: :delete, data: { confirm: "Are you sure you want to Delete your submission?" }, class: "btn btn-dark" %>
    <% end %>
  </div>
</div>

app/views/submissions/new.html.erb
<div class="container">
  <div class="tracks-form">
  <h1>Submit your part</h1>
  <h2 style="font-size: 19px !important">
    To collaborate with
    <%= @request.track.user.username %>
    on
    <%= @request.track.name %>
  </h2>
      <p class="mt-4"></p>
      <%= simple_form_for ([@request, @submission]) do |s| %>
        <%= s.input :description, label: 'Short description of your collaboration'%>
        <!-- <div class="row">
          <div class="col-6">
            <%= s.input :bpm %>
          </div>
          <div class="col-6">
            <%= s.input :time_signature %>
          </div>
        </div>
        <div class="row">
          <div class="col-6">
            <%= s.input :key %>
          </div>
          <div class="col-6">
            <%= s.input :duration %>
          </div>
        </div> -->
        <%= s.input :file %>
        <%= s.submit "Collaborate", class: "btn btn-primary"%>
      <% end %>
    </div>
</div>